name: Documentation Update
description: Suggest improvements or corrections to the documentation (README, guides, or other docs).
title: "docs: "
labels: [documentation]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Update
        Use this template to propose changes, corrections, or additions to the project documentation.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the documentation update.
      placeholder: "Example: Add missing setup instructions in README.md"
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation Behavior
      description: What is wrong, unclear, or missing in the current documentation?
    validations:
      required: true

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Improvement
      description: Describe the specific change you propose.
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Affected Files/Sections
      description: List the files or sections of documentation that need to be updated.
      placeholder: |
        - README.md (Setup section)
        - CONTRIBUTING.md (Git setup instructions)

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any extra details, references, or screenshots that can help.
      placeholder: "Screenshots, commit references, or related issues."
