name: Feature Request
description: Suggest a new idea, feature, or enhancement.
title: "feat: "
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Please describe your feature idea clearly to help us evaluate and prioritize it.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: Provide a short title or summary of your idea.
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case / Problem
      description: What problem will this feature solve? Why is it needed?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Suggested Solution
      description: How do you propose solving this problem?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Did you consider any other solutions?
      placeholder: "Using predefined templates or example text."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add references, designs, or screenshots if available.
